### ISSUE TITLE
[PRL21.5 Minor Bug] Old Aperture: Piston Platafrom PeTi Model is "Unstyled"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#707]
![20160819004904_1](https://cloud.githubusercontent.com/assets/12244376/17798698/0f1d971c-65aa-11e6-80ee-24f9d42eebd7.jpg)

**Comment by Luke18033** [comment]
Fixed now?

**Comment by LautaroL20** [comment]
@Luke18033 - Well, even if its not fixed i could make a styled model for it in Blender, since its not an animated one.

**Comment by TeamSpen210** [comment]
The ingame version is a model now, so we can copy it across pretty easy.
